[package]
name = "lrclib-api-rs"
version = "0.1.0"
edition = "2021"
authors = ["mokurin000"]
description = "LRCLib API Wrapper."
license = "MIT"

[dependencies]
http = "1.1.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "2.0.0"
